[Bug] Fix `tests/compile/test_config.py` AttributeError: 'NoneType' object has no attribute 'dtype' (#41288)
Signed-off-by: yewentao256 <zhyanwentao@126.com>
(cherry picked from commit 3e1ad4435f7c205dcbd5b14d1a529cc328b22ce8)